import React from 'react'

export const metadata={
    title:{
        default:"Auth | chai or code",
        template:"%s | chai or code",
        absolute: "",
    },
    description:'Generated by create next app',
}

const AuthLayout = ({children}) => {
  return (
    <div>{children}</div>
  )
}

export default AuthLayout